### ISSUE TITLE
Job duplizieren funktioniert nicht

### ISSUE THREAD

**Issue by mentor2k1** [sowieso-web/contao-jobposting-bundle#14]
Wenn man mit dem + einen Job duplizieren möchte, funktioniert das nicht. Die Seite lädt direkt neu, aber es erscheint keine Kopie

**Comment by Xirdion** [comment]
Hallo @mentor2k1 Ich konnte das Verhalten nicht reproduzieren.
Kannst du mir weitere Infos dazu geben, damit ich das Verhalten nachstellen kann?
