### ISSUE TITLE
Verschieben zwischen Job-Archiven 

### ISSUE THREAD

**Issue by mentor2k1** [sowieso-web/contao-jobposting-bundle#15]
Es fehlt eine Funktion, mit der man Jobs zwischen 2 Jobarchiven verschieben kann, bzw, lässt sich das irgendwie anders regeln? In der Maske gibt es dazu leider kein Feld, wo man das ggf. ändern kann.

**Comment by Xirdion** [comment]
Thanks @mentor2k1 for the input.
With version 1.0.13 it is now possible to move jobs between different archives.
