### ISSUE TITLE
1.0.13 ist nicht mehr kompatibel mit Contao 4.9

### ISSUE THREAD

**Issue by leonexcc** [sowieso-web/contao-jobposting-bundle#16]
Die Konstante DataContainer::MODE_PARENT gibt es in Contao 4.9 noch nicht und daher gibt es hier einen Fehler. Da Contao 4.9 noch supported wird, wäre es schon wenn es dazu kompatibel bleibt.

**Comment by Xirdion** [comment]
Danke für den Hinweis. Ich werden dem nachgehen udn den Code anpassen.

**Comment by Xirdion** [comment]
Mit Version 1.0.14 ist der Fehler nun behoben und das Bundle sollte auch unter Contao 4.9 wieder funktionieren.
